.TH UNRM "1" "June 2000" "unrm"
.SH NAME
unrm \- recover erased data
.SH SYNOPSIS
.B unrm
[\fIpartition\fR] [\fI-u file_owner\fR] [\fI-s string\fR]
.SH DESCRIPTION
unrm v0.9 is the stable version of a powerful shell utility which allows you
to recover erased data from a ext2 file system.
.PP
.SH OPTIONS
.TP
.BI \<partition> \ 
The ext2fs where the erased data used to be.
.TP
.BI \-u\ <owner>
Recovers only the files previously owned by 'owner'
.TP
.BI \-s\ <string>
Recovers only the files which used to contain the string 'string'
.SH "SEE ALSO"
.B debugfs(8)
,
.B The Linux Ext2fs Undeletion Mini-HOWTO
